import pyautogui
import webbrowser as wb
import time

wb.open("web.whatsapp.com")
time.sleep(30)
for i in range(400):
    pyautogui.press("D")
    pyautogui.press("o")
    pyautogui.press(" ")
    pyautogui.press("y")
    pyautogui.press("o")
    pyautogui.press("u")
    pyautogui.press(" ")
    pyautogui.press("k")
    pyautogui.press("n")
    pyautogui.press("o")
    pyautogui.press("w")
    pyautogui.press(" ")
    pyautogui.press("w")
    pyautogui.press("h")
    pyautogui.press("o")
    pyautogui.press(" ")
    pyautogui.press("e")
    pyautogui.press("l")
    pyautogui.press("s")
    pyautogui.press("e")
    pyautogui.press(" ")
    pyautogui.press("s")
    pyautogui.press("u")
    pyautogui.press("f")
    pyautogui.press("f")
    pyautogui.press("e")
    pyautogui.press("r")
    pyautogui.press("s")
    pyautogui.press(" ")
    pyautogui.press("f")
    pyautogui.press("r")
    pyautogui.press("o")
    pyautogui.press("m")
    pyautogui.press(" ")
    pyautogui.press("d")
    pyautogui.press("e")
    pyautogui.press("m")
    pyautogui.press("e")
    pyautogui.press("n")
    pyautogui.press("t")
    pyautogui.press("i")
    pyautogui.press("a")
    pyautogui.press("?")
    pyautogui.press(" ")
    pyautogui.press(":")
    pyautogui.press("D")
    pyautogui.press("enter")
